image: gcc:13.2.0@sha256:f993601701a37bef71e7f8fc1ef9410b09b15556f4371b06dcc10202cc81f9ea

aliases:
  build:
    script:
      - g++ --static -o chal engine.cpp runner.cpp -Wall -Werror -fno-toplevel-reorder -fPIC
