apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: babypwn2
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: kind/healthcheck:b953562afa7f2be6b40b4035292a56a6e37d84856e334a22a00897e2e29cde6f
  image: kind/challenge:e3588691a479b85b56bcfaa9d4559818cf93c6176c8abbd8ba0e002af011954e
